# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TraceGeometricNetwork.py
# Created on: 2017-06-14 15:18:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: TraceGeometricNetwork <Flags> <Barriers> <Sysvalves_Layer> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
Flags = arcpy.GetParameterAsText(0)
if Flags == '#' or not Flags:
    Flags = "in_memory\\{DE3853E4-C522-4F48-AE24-8FD4BA0B58BD}" # provide a default value if unspecified

Barriers = arcpy.GetParameterAsText(1)
if Barriers == '#' or not Barriers:
    Barriers = "in_memory\\{06750857-018E-4C94-8D7F-A45A9AC7B1AF}" # provide a default value if unspecified

Sysvalves_Layer = arcpy.GetParameterAsText(2)
if Sysvalves_Layer == '#' or not Sysvalves_Layer:
    Sysvalves_Layer = "Sysvalves_Layer" # provide a default value if unspecified

# Local variables:
Water_Net = "C:\\Users\\mpatel1\\Downloads\\GP_Service_Examples10_2_1\\GP Service Examples\\TraceGeometricNetwork\\ToolData\\Montgomery.gdb\\Water\\Water_Net"
Flag_Locations = Flags
Distribution_mains = "Distribution mains"
Barrier_Locations = Distribution_mains
Accumulation_Cost = "-1"
traceResults = "traceResults"
Sysvalves = traceResults

# Process: Snap
arcpy.Snap_edit(Flags, "'Distribution mains' EDGE '10 Unknown'")

# Process: Snap (2)
arcpy.Snap_edit(Barriers, "'Distribution mains' EDGE '10 Unknown'")

# Process: Trace Geometric Network
arcpy.TraceGeometricNetwork_management(Water_Net, traceResults, Flag_Locations, "TRACE_UPSTREAM", Barrier_Locations, "", "", "", "", "NO_TRACE_ENDS", "", "", "", "AS_IS", "", "", "", "AS_IS")

# Process: Select Data
arcpy.SelectData_management(traceResults, "Sysvalves")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Sysvalves, Sysvalves_Layer, "", "", "")

